# Generated by Django 5.1.2 on 2025-01-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0003_invoice_billingnumber'),
        ('adminsection', '0004_auto_20200131_0814'),
    ]

    operations = [
    ]
