# Generated by Django 5.1.2 on 2025-01-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_appoinment_appointmentnumber'),
        ('parlour', '0014_auto_20200125_2045'),
    ]

    operations = [
    ]
